# preparação

In [ ]:
import os
if os.path.exists("producao_linha_A.csv"):
  print ("arquivo encontrado, bora começar")
else:
  print ("não econtrei o arquivo")

arquivo encontrado, bora começar

# carregar a base de dados

In [ ]:
import csv

registro = []
with open ("producao_linha_A.csv" , encoding = 'utf-8') as f:
  leitor = csv.DictReader(f)
  for linha in leitor:
    registro.append(linha)

print("total de registros:" , len(registro))
print("número de registros é assim: ")
print(registro[0])

total de registros: 25
número de registros é assim:
{'id_registro': '25', 'data': '2026-08-07', 'turno': 'Tarde ', 'codigo_peca': 'PC-200', 'qtd_produzida': '905', 'qtd_refugo': '11', 'temperatura_c': '70.3', 'status': 'OK'}

In [ ]:
#campos principais de cada registro, numerados

print("ID  | Data       | Turno   | Peça    | Produzido | Refugo | Temp   | Status")
print("-" * 75)
for r in registro:
  print(f"{r['id_registro']:>3} | {r['data']:<10} | {r['turno']:<7} | {r['codigo_peca']:<7} | {r['qtd_produzida']:>9} | {r['qtd_refugo']:>6} | {r['temperatura_c']:<6} | {r['status']:<6}")

ID  | Data       | Turno   | Peça    | Produzido | Refugo | Temp   | Status
---------------------------------------------------------------------------
  1 | 2026-08-03 | Manhã   | PC-100  |       850 |     12 | 71.5   | OK
  2 | 2026-08-03 | manha   | PC-100  |       830 |     20 | 72.1   | OK
  3 | 2026-08-03 | Tarde   | pc-200  |       910 |      8 | 70.9   | OK
  4 | 2026-08-03 | Tarde   | PC-200  |       780 |     45 | 73.4   | NOK
  5 | 2026-08-03 | Noite   | PC-100  |       640 |     15 | 71.0   | OK
  6 | 2026-08-04 | MANHÃ   | PC-300  |       720 |     10 | 72.8   | OK
  7 | 2026-08-04 | Manhã   | PC-300  |       720 |     10 | 72.8   | OK
  8 | 2026-08-04 | Tarde   | PC-100  |       895 |      9 | 70.2   | OK
  9 | 2026-08-04 | tarde   | PC-200  |       610 |     55 | 74.9   | NOK
 10 | 2026-08-04 | Noite   | PC-300  |       580 |     18 | 999.0  | OK
 11 | 2026-08-05 | Manhã   | PC-100  |       870 |      7 | 71.9   | OK
 12 | 2026-08-05 | Manhã   | PC-100  |       870 |      7 | 71.9   | OK
 13 | 2026-08-05 | Tarde   | PC-200  |       900 |     11 | 70.5   | OK
 14 | 2026-08-05 |         | PC-300  |       660 |     14 | 72.0   | OK
 15 | 2026-08-05 | Noite   | PC-100  |       -50 |     13 | 71.3   | OK
 16 | 2026-08-06 | Manhã   | PC-200  |       815 |     16 | 72.6   | OK
 17 | 2026-08-06 | Tarde   | PC-300  |       705 |     40 | 73.9   | NOK
 18 | 2026-08-06 | Tarde   | PC-300  |       705 |     40 | 73.9   | NOK
 19 | 2026-08-06 | Noite   |         |       590 |     12 | 70.8   | OK
 20 | 2026-08-06 | manhã   | PC-100  |       848 |      9 | 71.4   | OK
 21 | 2026-08-07 | Manhã   | PC-200  |       862 |     10 | 72.2   | OK
 22 | 2026-08-07 | Tarde   | PC-100  |       889 |      8 | 70.6   | OK
 23 |            |         |         |           |        |        |
 24 | 2026-08-07 | Noite   | PC-300  |       575 |     19 | 71.7   | OK
 25 | 2026-08-07 | Tarde   | PC-200  |       905 |     11 | 70.3   | OK

In [ ]:
for r in registros:
  valores = [r'data' , r'turno' , r'codigo_peca' , r "qtd_produzido" , r 'qtd_refugo' , r 'temperaura_c , r ' status'
  if all (v.strip()

In [ ]:
turno_antes = set(r['turno'] for r in registros
            )

In [ ]:
# Padronização
for r in registro:
    turno = r["turno"].strip().lower()
    if turno in ["manha", "manhã"]:
        r["turno"] = "Manhã"
    elif turno == "tarde":
        r["turno"] = "Tarde"
    elif turno == "noite":
        r["turno"] = "Noite"
    elif turno == "":
        r["turno"] = "Não informado"
    else:
        r["turno"] = turno.capitalize()

turno_depois = set(r["turno"] for r in registro)
print("Turnos depois da padronização:", turno_depois)

Turnos depois da padronização: {'Manhã', 'Noite', 'Não informado', 'Tarde'}

## encontrar arquivo

In [ ]:
import os
if os.path.exists('producao_linha_A.csv'):
  print ("Arquivo Encontrado")
else:
  print('Arquivo não encontrado')

Arquivo Encontrado

# pandas

In [ ]:
import pandas as pd
print("pandas pronto!")

pandas pronto!

# carregar o arquivo com dataframe

In [ ]:
df = pd.read_csv("producao_linha_A.csv")
print("arquivo carregado")

arquivo carregado

# funções dataframe

In [ ]:
df.shape

(25, 8)

In [ ]:
df.head()

,id_registro,data,turno,codigo_peca,qtd_produzida,qtd_refugo,temperatura_c,status
0,1,2026-08-03,Manhã,PC-100,850.0,12.0,71.5,OK
1,2,2026-08-03,manha,PC-100,830.0,20.0,72.1,OK
2,3,2026-08-03,Tarde,pc-200,910.0,8.0,70.9,OK
3,4,2026-08-03,Tarde,PC-200,780.0,45.0,73.4,NOK
4,5,2026-08-03,Noite,PC-100,640.0,15.0,71.0,OK

In [ ]:
df

,id_registro,data,turno,codigo_peca,qtd_produzida,qtd_refugo,temperatura_c,status
0,1,2026-08-03,Manhã,PC-100,850.0,12.0,71.5,OK
1,2,2026-08-03,manha,PC-100,830.0,20.0,72.1,OK
2,3,2026-08-03,Tarde,pc-200,910.0,8.0,70.9,OK
3,4,2026-08-03,Tarde,PC-200,780.0,45.0,73.4,NOK
4,5,2026-08-03,Noite,PC-100,640.0,15.0,71.0,OK
5,6,2026-08-04,MANHÃ,PC-300,720.0,10.0,72.8,OK
6,7,2026-08-04,Manhã,PC-300,720.0,10.0,72.8,OK
7,8,2026-08-04,Tarde,PC-100,895.0,9.0,70.2,OK
8,9,2026-08-04,tarde,PC-200,610.0,55.0,74.9,NOK
9,10,2026-08-04,Noite,PC-300,580.0,18.0,999.0,OK
10,11,2026-08-05,Manhã,PC-100,870.0,7.0,71.9,OK
11,12,2026-08-05,Manhã,PC-100,870.0,7.0,71.9,OK
12,13,2026-08-05,Tarde,PC-200,900.0,11.0,70.5,OK
13,14,2026-08-05,NaN,PC-300,660.0,14.0,72.0,OK
14,15,2026-08-05,Noite,PC-100,-50.0,13.0,71.3,OK
15,16,2026-08-06,Manhã,PC-200,815.0,16.0,72.6,OK
16,17,2026-08-06,Tarde,PC-300,705.0,40.0,73.9,NOK
17,18,2026-08-06,Tarde,PC-300,705.0,40.0,73.9,NOK
18,19,2026-08-06,Noite,NaN,590.0,12.0,70.8,OK
19,20,2026-08-06,manhã,PC-100,848.0,9.0,71.4,OK
20,21,2026-08-07,Manhã,PC-200,862.0,10.0,72.2,OK
21,22,2026-08-07,Tarde,PC-100,889.0,8.0,70.6,OK
22,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,24,2026-08-07,Noite,PC-300,575.0,19.0,71.7,OK
24,25,2026-08-07,Tarde,PC-200,905.0,11.0,70.3,OK

In [ ]:
#diagnóstico do que está faltando

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_registro    25 non-null     int64
 1   data           24 non-null     object
 2   turno          23 non-null     object
 3   codigo_peca    23 non-null     object
 4   qtd_produzida  24 non-null     float64
 5   qtd_refugo     24 non-null     float64
 6   temperatura_c  24 non-null     float64
 7   status         24 non-null     object
dtypes: float64(3), int64(1), object(4)
memory usage: 1.7+ KB

In [ ]:
df.isnull().sum()

id_registro      0
data             1
turno            2
codigo_peca      2
qtd_produzida    1
qtd_refugo       1
temperatura_c    1
status           1
dtype: int64

# remover linha vazia

In [ ]:
colunas = [
    "data",
    "turno",
    'codigo_peca',
    'qtd_produzida',
    'qtd_refugo',
    'temperatura_c',
    'status'
]

df = df.dropna(subset=colunas, how='all')
print('linhas agora:', df.shape[0])

linhas agora: 21

# padronizacao turnos

In [ ]:
from enum import unique
#padronização do turno

df['turno'].unique()

# tira espaço e deixa minusculo

df['turno'] = df['turno'].str.strip().str.lower()

#troca pelos nomes corretos
df['turno'] = df['turno'].replace({
    'manha': 'Manha',
    "manhã": 'Manha',
    'tarde': "Tarde",
    'noite': 'Noite'
})
#conferindo
df['turno'].unique()

array(['Manha', 'Tarde', 'Noite', nan], dtype=object)

# padronizacao peças

In [ ]:
from enum import unique
#padronizar

df['codigo_peca'] = df['codigo_peca'].str.strip().str.upper()
df['codigo_peca'].unique

#remover duplicados

antes = df.shape[0]
df = df.drop_duplicates(subset= colunas)
print (f'Antes: {antes} , Depois: {df.shape[0]}')
print ('duplicados removidos:' , antes - df.shape[0])

#tratar valores impossíveis

df.loc[df['qtd_produzida'] < 0, 'qtd_´produzida'] = None
df.loc[df['temperatura_c'] >200, 'temperatura_c'] = None
print("valores impossíveis tratados")

df

Antes: 21 , Depois: 21
duplicados removidos: 0
valores impossíveis tratados

,id_registro,data,turno,codigo_peca,qtd_produzida,qtd_refugo,temperatura_c,status,qtd_´produzida
0,1,2026-08-03,Manha,PC-100,850.0,12.0,71.5,OK,NaN
1,2,2026-08-03,Manha,PC-100,830.0,20.0,72.1,OK,NaN
2,3,2026-08-03,Tarde,PC-200,910.0,8.0,70.9,OK,NaN
3,4,2026-08-03,Tarde,PC-200,780.0,45.0,73.4,NOK,NaN
4,5,2026-08-03,Noite,PC-100,640.0,15.0,71.0,OK,NaN
5,6,2026-08-04,Manha,PC-300,720.0,10.0,72.8,OK,NaN
7,8,2026-08-04,Tarde,PC-100,895.0,9.0,70.2,OK,NaN
8,9,2026-08-04,Tarde,PC-200,610.0,55.0,74.9,NOK,NaN
9,10,2026-08-04,Noite,PC-300,580.0,18.0,NaN,OK,NaN
10,11,2026-08-05,Manha,PC-100,870.0,7.0,71.9,OK,NaN
12,13,2026-08-05,Tarde,PC-200,900.0,11.0,70.5,OK,NaN
13,14,2026-08-05,NaN,PC-300,660.0,14.0,72.0,OK,NaN
14,15,2026-08-05,Noite,PC-100,-50.0,13.0,71.3,OK,None
15,16,2026-08-06,Manha,PC-200,815.0,16.0,72.6,OK,NaN
16,17,2026-08-06,Tarde,PC-300,705.0,40.0,73.9,NOK,NaN
18,19,2026-08-06,Noite,NaN,590.0,12.0,70.8,OK,NaN
19,20,2026-08-06,Manha,PC-100,848.0,9.0,71.4,OK,NaN
20,21,2026-08-07,Manha,PC-200,862.0,10.0,72.2,OK,NaN
21,22,2026-08-07,Tarde,PC-100,889.0,8.0,70.6,OK,NaN
23,24,2026-08-07,Noite,PC-300,575.0,19.0,71.7,OK,NaN
24,25,2026-08-07,Tarde,PC-200,905.0,11.0,70.3,OK,NaN

In [ ]:
df['temperatura_c'].describe()

count    20.000000
mean     71.800000
std       1.244356
min      70.200000
25%      70.875000
50%      71.600000
75%      72.300000
max      74.900000
Name: temperatura_c, dtype: float64

# utilizando agrupamentos

In [ ]:
from itertools import groupby
df.groupby("turno")['qtd_refugo'].mean().round(1)

turno
Manha    12.0
Noite    15.4
Tarde    23.4
Name: qtd_refugo, dtype: float64

# salvar a base de dados

In [ ]:
df.to_csv('producao_limpa.csv', index=False)
print('Base limpa salva')
print('Tamanho final:' , df.shape)

Base limpa salva
Tamanho final: (21, 9)