In [ ]:
import pandas as pd
import numpy as np

print ("importação realizada")

importação realizada

In [ ]:
#lendo os dados
df = pd.read_csv("/content/producao_estatistica.csv")
print(df)

      id turno maquina  tempo_ciclo  refugo_pct  temperatura  vibracao  \
0      1     A     M01         39.7         3.2         71.7     0.018
1      2     A     M03         41.3         2.6         72.3     0.041
2      3     A     M03         39.1         1.5         70.5     0.032
3      4     A     M01         37.9         2.9         72.7     0.043
4      5     A     M01         44.8         3.6         69.1     0.021
..   ...   ...     ...          ...         ...          ...       ...
195  196     B     M02         33.3         3.5         82.3     0.040
196  197     A     M02         38.3         2.6         72.9     0.031
197  198     B     M03         40.7         5.0         78.1     0.066
198  199     B     M03         39.9         3.5         82.3     0.043
199  200     B     M03         54.4         6.1         75.7     0.062

    operador
0       Lima
1      Costa
2       Lima
3       Lima
4      Costa
..       ...
195    Alves
196     Lima
197    Souza
198    Alves
199    Alves

[200 rows x 8 columns]

## media manual

In [ ]:
#extraindo tempo_ciclo como list

tempos = df['tempo_ciclo'].tolist()

#média
soma = sum(tempos)

valores = len(tempos)
media_manual = soma/valores

print(f'soma: {soma:.1f}')
print(f'quantidade: {valores:.1f}')
print(f"média manual: {media_manual:.2f}")

soma: 8615.3
quantidade: 200.0
média manual: 43.08

## numpy

In [ ]:
media_numpy = np.mean(tempos)
print(f'média Numpy: {media_numpy:.2f}')

média Numpy: 43.08

## mediana

In [ ]:
#media do temppo de ciclo

print("média ", round(df['tempo_ciclo'].mean(), 2))

#mediana do tempo de ciclo

print('mediana ', round(df['tempo_ciclo'].median(), 2))

média  43.08
mediana  41.25

## comparando por turno

In [ ]:
#media por turno
df.groupby('turno')['tempo_ciclo'].mean()

df.groupby('turno')['tempo_ciclo'].median()

turno
A    39.9
B    44.6
Name: tempo_ciclo, dtype: float64

## desafio:
calcule a média e mediana de refugo_pct por máquina.

qual máquina tem mais refugo?

In [ ]:
df.groupby('maquina')['refugo_pct'].mean()
df.groupby('maquina')['refugo_pct'].median()

maquina
M01    3.3
M02    3.3
M03    3.3
Name: refugo_pct, dtype: float64

## desvio padrão

In [ ]:
#desvio padrão (dispersão)
print ('desvio padrão de dispersão: ', round(df['tempo_ciclo'].std(), 2), 'segundos')

#desvio padrão por turno
dp_por_turno = df.groupby('turno')['tempo_ciclo'].std()

desvio padrão de dispersão:  7.35 segundos
turno
A    6.160825
B    7.574792
Name: tempo_ciclo, dtype: float64 segundos

## exercicio com base de dados suja

In [ ]:
#importando a base e conferindo

import pandas as pd
import numpy as np

df = pd.read_csv('producao_bruta.csv')
print (df)

df.head()

      id turno maquina  tempo_ciclo  refugo_pct  temperatura  vibracao  \
0      1     A     M02         44.1         2.1         76.0     0.025
1      2     B     M03         51.6         1.4         69.4     0.051
2      3     B     M01         42.4         4.2         80.2     0.035
3      4     B     M03         46.3         6.8         89.4     0.046
4      5     B     M03         37.7         1.9         83.3     0.060
..   ...   ...     ...          ...         ...          ...       ...
220  216     B     M02         33.2         4.2         88.4     0.026
221  217     B     M01         43.2         6.7         78.4     0.051
222  218     A     M01         40.1         2.8         72.1     0.029
223  219     A     M01         38.9         3.4         72.2     0.010
224  220     B     M02         41.6         7.0         79.5     0.040

    operador
0       Lima
1      Alves
2      Souza
3    Pereira
4      Alves
..       ...
220    Alves
221    Souza
222     Lima
223    Silva
224    Souza

[225 rows x 8 columns]

   id turno maquina  tempo_ciclo  refugo_pct  temperatura  vibracao operador
0   1     A     M02         44.1         2.1         76.0     0.025     Lima
1   2     B     M03         51.6         1.4         69.4     0.051    Alves
2   3     B     M01         42.4         4.2         80.2     0.035    Souza
3   4     B     M03         46.3         6.8         89.4     0.046  Pereira
4   5     B     M03         37.7         1.9         83.3     0.060    Alves

In [ ]:
#diagnostico dos erros

#nulos

nulos = df.isnull().sum()
print(nulos)

#duplicatas

duplicatas = df.duplicated().sum()
print('há' , duplicatas , 'duplicatas')

#formatação errada

erros = df['turno'].unique()
print(erros)

#valores impossíveis

valores = df.describe()

print(valores)

id             0
turno          0
maquina        0
tempo_ciclo    2
refugo_pct     2
temperatura    2
vibracao       1
operador       1
dtype: int64
há 5 duplicatas
['A' 'B' 'a' ' B' 'A ']
               id  tempo_ciclo  refugo_pct  temperatura    vibracao
count  225.000000   223.000000  223.000000   223.000000  224.000000
mean   110.888889    42.519731    4.545291    78.912108    0.039036
std     63.546321     8.707446    7.647526    62.643289    0.015113
min      1.000000   -15.300000   -5.000000   -40.000000    0.010000
25%     56.000000    38.800000    2.300000    71.500000    0.028000
50%    111.000000    41.600000    3.400000    74.000000    0.036000
75%    166.000000    45.800000    5.600000    78.400000    0.048000
max    220.000000    81.300000  110.000000   999.900000    0.089000

limpeza

In [ ]:
#padronizando

df['turno'] = df['turno'].str.strip().str.upper()

df= df.drop_duplicates(subset= 'id')
print(df)

      id turno maquina  tempo_ciclo  refugo_pct  temperatura  vibracao  \
0      1     A     M02         44.1         2.1         76.0     0.025
1      2     B     M03         51.6         1.4         69.4     0.051
2      3     B     M01         42.4         4.2         80.2     0.035
3      4     B     M03         46.3         6.8         89.4     0.046
4      5     B     M03         37.7         1.9         83.3     0.060
..   ...   ...     ...          ...         ...          ...       ...
220  216     B     M02         33.2         4.2         88.4     0.026
221  217     B     M01         43.2         6.7         78.4     0.051
222  218     A     M01         40.1         2.8         72.1     0.029
223  219     A     M01         38.9         3.4         72.2     0.010
224  220     B     M02         41.6         7.0         79.5     0.040

    operador
0       Lima
1      Alves
2      Souza
3    Pereira
4      Alves
..       ...
220    Alves
221    Souza
222     Lima
223    Silva
224    Souza

[220 rows x 8 columns]

In [ ]:
#padronizando

colunas = [
    'id' ,
    'turno' ,
    'tempo_ciclo' ,
    'refugo_pct' ,
    'temperatura' ,
    'vibracao' ,
    'operador'
]

df_sem_duplicatas = df.drop_duplicates(subset= colunas)
print(df_sem_duplicatas)

df_branco = df_sem_duplicatas.dropna(subset= colunas, how= 'all')

      id turno maquina  tempo_ciclo  refugo_pct  temperatura  vibracao  \
0      1     A     M02         44.1         2.1         76.0     0.025
1      2     B     M03         51.6         1.4         69.4     0.051
2      3     B     M01         42.4         4.2         80.2     0.035
3      4     B     M03         46.3         6.8         89.4     0.046
4      5     B     M03         37.7         1.9         83.3     0.060
..   ...   ...     ...          ...         ...          ...       ...
220  216     B     M02         33.2         4.2         88.4     0.026
221  217     B     M01         43.2         6.7         78.4     0.051
222  218     A     M01         40.1         2.8         72.1     0.029
223  219     A     M01         38.9         3.4         72.2     0.010
224  220     B     M02         41.6         7.0         79.5     0.040

    operador
0       Lima
1      Alves
2      Souza
3    Pereira
4      Alves
..       ...
220    Alves
221    Souza
222     Lima
223    Silva
224    Souza

[220 rows x 8 columns]

In [ ]:
#removendo valores impossiveis
df_limpo = df_branco[
    (df_branco['tempo_ciclo'] > 0) &
    (df_branco['refugo_pct'] >= 0) & (df_branco['refugo_pct'] <= 100) &
    (df_branco['temperatura'] >= 0) & (df_branco['temperatura'] <= 200)
]

print(df_limpo.head())

   id turno maquina  tempo_ciclo  refugo_pct  temperatura  vibracao operador
0   1     A     M02         44.1         2.1         76.0     0.025     Lima
1   2     B     M03         51.6         1.4         69.4     0.051    Alves
2   3     B     M01         42.4         4.2         80.2     0.035    Souza
3   4     B     M03         46.3         6.8         89.4     0.046  Pereira
4   5     B     M03         37.7         1.9         83.3     0.060    Alves

In [ ]:
# Conferencia final do df_limpo

print("\n--- Valores nulos por coluna no df_limpo ---")
df_nulo_final = df_limpo.isnull().sum()
print(df_nulo_final)

print("\n--- Numero de linhas duplicadas no df_limpo ---")
duplicatas_final = df_limpo.duplicated().sum()
print(f'Há {duplicatas_final} duplicatas.')

print("\n--- Estatísticas descritivas do df_limpo ---")
df_final_describe = df_limpo.describe()
print(df_final_describe)

--- Valores nulos por coluna no df_limpo ---
id             0
turno          0
maquina        0
tempo_ciclo    0
refugo_pct     0
temperatura    0
vibracao       1
operador       1
dtype: int64

--- Numero de linhas duplicadas no df_limpo ---
Há 0 duplicatas.

--- Estatísticas descritivas do df_limpo ---
               id  tempo_ciclo  refugo_pct  temperatura    vibracao
count  208.000000   208.000000  208.000000   208.000000  207.000000
mean   110.658654    43.138942    4.175000    75.205288    0.039469
std     63.538522     7.352943    2.855074     5.140699    0.015143
min      1.000000    30.400000    0.000000    64.600000    0.010000
25%     55.750000    38.800000    2.300000    71.550000    0.028000
50%    110.500000    41.700000    3.500000    73.650000    0.036000
75%    165.250000    46.050000    5.825000    78.400000    0.048000
max    220.000000    81.300000   20.100000    90.400000    0.089000

In [ ]:
print("\n--- Valores nulos por coluna no df_limpo ---")
df_nulo_final = df_limpo.isnull().sum()
print(df_nulo_final)

print("\n--- Numero de linhas duplicadas no df_limpo ---")
duplicatas_final = df_limpo.duplicated().sum()
print(f'Há {duplicatas_final} duplicatas.')

print("\n--- Estatísticas descritivas do df_limpo ---")
df_final_describe = df_limpo.describe()
print(df_final_describe)

--- Valores nulos por coluna no df_limpo ---
id             0
turno          0
maquina        0
tempo_ciclo    0
refugo_pct     0
temperatura    0
vibracao       1
operador       1
dtype: int64

--- Numero de linhas duplicadas no df_limpo ---
Há 0 duplicatas.

--- Estatísticas descritivas do df_limpo ---
               id  tempo_ciclo  refugo_pct  temperatura    vibracao
count  208.000000   208.000000  208.000000   208.000000  207.000000
mean   110.658654    43.138942    4.175000    75.205288    0.039469
std     63.538522     7.352943    2.855074     5.140699    0.015143
min      1.000000    30.400000    0.000000    64.600000    0.010000
25%     55.750000    38.800000    2.300000    71.550000    0.028000
50%    110.500000    41.700000    3.500000    73.650000    0.036000
75%    165.250000    46.050000    5.825000    78.400000    0.048000
max    220.000000    81.300000   20.100000    90.400000    0.089000

In [ ]:
from typing_extensions import final
#média e mediana

#soma de tempo_ciclo

soma_tempo_ciclo = df_final_describe['tempo_ciclo'].sum()

#qtd de itens em tempo ciclo
qtd_tempo_ciclo = len(df_final_describe['tempo_ciclo'])

#media manual
media_manual_tempo_ciclo = soma_tempo_ciclo / qtd_tempo_ciclo

print(f"Soma de tempo_ciclo: {soma_tempo_ciclo:.2f}")
print(f"Quantidade de tempo_ciclo: {qtd_tempo_ciclo}")
print(f"Média manual de tempo_ciclo: {media_manual_tempo_ciclo:.2f}")

media_tempo_ciclo = df_final_describe['tempo_ciclo'].mean()
print(f"Média de tempo_ciclo com .mean(): {media_tempo_ciclo:.2f}")
print(f"A média manual e a média com .mean() são {'iguais' if abs(media_tempo_ciclo - media_tempo_ciclo) < 0.001 else 'diferentes'}.")

Soma de tempo_ciclo: 496.74
Quantidade de tempo_ciclo: 8
Média manual de tempo_ciclo: 62.09
Média de tempo_ciclo com .mean(): 62.09
A média manual e a média com .mean() são iguais.

In [ ]:
#mediana
mediana_tempo_ciclo = df_final_describe['tempo_ciclo'].median()
print(f"Mediana de tempo_ciclo: {mediana_tempo_ciclo:.2f}")

Mediana de tempo_ciclo: 41.70

In [ ]:
media_tempo_ciclo_por_turno = df_limpo.groupby('turno')['tempo_ciclo'].mean()
mediana_tempo_ciclo_por_turno = df_limpo.groupby('turno')['tempo_ciclo'].median()

print("Média de tempo_ciclo por turno:")
print(media_tempo_ciclo_por_turno)
print("\nMediana de tempo_ciclo por turno:")
print(mediana_tempo_ciclo_por_turno)

Média de tempo_ciclo por turno:
turno
 B    39.500000
A     40.237895
A     41.600000
B     45.722727
a     39.700000
Name: tempo_ciclo, dtype: float64

Mediana de tempo_ciclo por turno:
turno
 B    39.5
A     39.7
A     41.6
B     45.6
a     39.7
Name: tempo_ciclo, dtype: float64

In [ ]:
#para refugo pct

media_refugo_pct = df_limpo['refugo_pct'].mean()
print(f"Média de refugo_pct: {media_refugo_pct:.2f}")

#comparaçao

media_refugo_pct_por_turno = df_limpo.groupby('turno')['refugo_pct'].mean()
mediana_refugo_pct_por_turno = df_limpo.groupby('turno')['refugo_pct'].median()

print("Média de refugo_pct por turno:")
print(media_refugo_pct_por_turno)
print("\nMediana de refugo_pct por turno:")
print(mediana_refugo_pct_por_turno)

Média de refugo_pct: 4.18
Média de refugo_pct por turno:
turno
 B    8.200000
A     2.715789
A     3.500000
B     5.421818
a     2.300000
Name: refugo_pct, dtype: float64

Mediana de refugo_pct por turno:
turno
 B    8.20
A     2.50
A     3.50
B     5.35
a     2.30
Name: refugo_pct, dtype: float64

In [ ]:
# Recarregando o DataFrame original para garantir que começamos do zero com as modificações
df = pd.read_csv('producao_bruta.csv')

# 1. Padronizando a coluna 'turno': removendo espaços e convertendo para maiúsculas
df['turno'] = df['turno'].str.strip().str.upper()
print("Valores únicos de 'turno' após padronização inicial:")
print(df['turno'].unique())

Valores únicos de 'turno' após padronização inicial:
['A' 'B']

In [ ]:
# 2. Removendo duplicatas com base em um subconjunto de colunas
# (Mantendo a lógica de JEyHNQNbMS7v que considera múltiplas colunas para duplicatas)
colunas_para_duplicatas = [
    'id',
    'turno',
    'tempo_ciclo',
    'refugo_pct',
    'temperatura',
    'vibracao',
    'operador'
]
df_sem_duplicatas = df.drop_duplicates(subset=colunas_para_duplicatas)

print(f"Linhas após remover duplicatas: {len(df_sem_duplicatas)}")

Linhas após remover duplicatas: 220

In [ ]:
# 3. Removendo linhas onde todas as colunas especificadas são nulas
# (Mantendo a lógica de JEyHNQNbMS7v)
# 'id' não deve ser usado aqui se for a chave primária e não tiver nulos no original
df_branco = df_sem_duplicatas.dropna(subset=colunas_para_duplicatas, how='all')

print(f"Linhas após remover linhas com todas as colunas nulas: {len(df_branco)}")

Linhas após remover linhas com todas as colunas nulas: 220

In [ ]:
# 4. Removendo valores impossíveis (Mantendo a lógica de 2bfb2447)
df_limpo = df_branco[
    (df_branco['tempo_ciclo'] > 0) &
    (df_branco['refugo_pct'] >= 0) & (df_branco['refugo_pct'] <= 100) &
    (df_branco['temperatura'] >= 0) & (df_branco['temperatura'] <= 200)
]

print(f"Linhas finais em df_limpo após remover valores impossíveis: {len(df_limpo)}")
print("\nVerificando os valores únicos de 'turno' no df_limpo atualizado:")
print(df_limpo['turno'].unique())

Linhas finais em df_limpo após remover valores impossíveis: 208

Verificando os valores únicos de 'turno' no df_limpo atualizado:
['A' 'B']

In [ ]:
media_tempo_ciclo_por_turno = df_limpo.groupby('turno')['tempo_ciclo'].mean()
mediana_tempo_ciclo_por_turno = df_limpo.groupby('turno')['tempo_ciclo'].median()

print("Média de tempo_ciclo por turno (df_limpo atualizado):")
print(media_tempo_ciclo_por_turno)
print("\nMediana de tempo_ciclo por turno (df_limpo atualizado):")
print(mediana_tempo_ciclo_por_turno)

Média de tempo_ciclo por turno (df_limpo atualizado):
turno
A    40.246392
B    45.666667
Name: tempo_ciclo, dtype: float64

Mediana de tempo_ciclo por turno (df_limpo atualizado):
turno
A    39.7
B    45.6
Name: tempo_ciclo, dtype: float64

In [ ]:
media_refugo_pct = df_limpo['refugo_pct'].mean()
print(f"Média geral de refugo_pct (df_limpo atualizado): {media_refugo_pct:.2f}")

media_refugo_pct_por_turno = df_limpo.groupby('turno')['refugo_pct'].mean()
mediana_refugo_pct_por_turno = df_limpo.groupby('turno')['refugo_pct'].median()

print("\nMédia de refugo_pct por turno (df_limpo atualizado):")
print(media_refugo_pct_por_turno)
print("\nMediana de refugo_pct por turno (df_limpo atualizado):")
print(mediana_refugo_pct_por_turno)

Média geral de refugo_pct (df_limpo atualizado): 4.18

Média de refugo_pct por turno (df_limpo atualizado):
turno
A    2.719588
B    5.446847
Name: refugo_pct, dtype: float64

Mediana de refugo_pct por turno (df_limpo atualizado):
turno
A    2.5
B    5.4
Name: refugo_pct, dtype: float64

In [ ]:
print(df_limpo)

      id turno maquina  tempo_ciclo  refugo_pct  temperatura  vibracao  \
0      1     A     M02         44.1         2.1         76.0     0.025
1      2     B     M03         51.6         1.4         69.4     0.051
2      3     B     M01         42.4         4.2         80.2     0.035
3      4     B     M03         46.3         6.8         89.4     0.046
4      5     B     M03         37.7         1.9         83.3     0.060
..   ...   ...     ...          ...         ...          ...       ...
220  216     B     M02         33.2         4.2         88.4     0.026
221  217     B     M01         43.2         6.7         78.4     0.051
222  218     A     M01         40.1         2.8         72.1     0.029
223  219     A     M01         38.9         3.4         72.2     0.010
224  220     B     M02         41.6         7.0         79.5     0.040

    operador
0       Lima
1      Alves
2      Souza
3    Pereira
4      Alves
..       ...
220    Alves
221    Souza
222     Lima
223    Silva
224    Souza

[208 rows x 8 columns]

## quartil

In [ ]:
q1 = df['tempo_ciclo'].quantile(0.25)

q3 = df['tempo_ciclo'].quantile(0.75)

iqr = q3 - q1

print('0.25%: ' , round(q1 , 2))
print('0.75%: ' , round(q3 , 2))
print('0.50%: ' , round(iqr, 2))

0.25%:  38.8
0.75%:  45.8
0.50%:  7.0

## outliers

In [ ]:
#limites

limitebaixo = q1 - 1.5 * iqr
limitealto = q3 - 1.5 * iqr

print('limite inferior ', round(limitebaixo, 2))
print('limite superior' , round(limitealto, 2))
print()
print(f'valores abaixo de {limitebaixo:.2f} ou acima de {limitealto:.2f} são outliers')

limite inferior  28.3
limite superior 35.3

valores abaixo de 28.30 ou acima de 35.30 são outliers

In [ ]:
#encontrado outliers

outliers = df[
    (df['tempo_ciclo'] < limitebaixo) |
    (df['tempo_ciclo'] > limitealto)
]

print('outliers encontrados: ' , len(outliers))
print()
outliers[['id' , 'turno' , 'maquina' , 'tempo_ciclo' , 'operador']]

outliers encontrados:  204

      id turno maquina  tempo_ciclo operador
0      1     A     M02         44.1     Lima
1      2     B     M03         51.6    Alves
2      3     B     M01         42.4    Souza
3      4     B     M03         46.3  Pereira
4      5     B     M03         37.7    Alves
..   ...   ...     ...          ...      ...
219  215     A     M01         38.1    Costa
221  217     B     M01         43.2    Souza
222  218     A     M01         40.1     Lima
223  219     A     M01         38.9    Silva
224  220     B     M02         41.6    Souza

[204 rows x 5 columns]

## probabilidade
- quantidade de vezes que algo acontece dividido pelo total de vezes

In [ ]:
#quantas peças tem refugo acima de 5%

total = len(df)
acima5 = len(df[df['refugo_pct']>5])

prob = acima5 / total

print(f'peças com refugo >5%: {acima5} de {total}')
print(f'probabilidade: {prob:.0%}')

peças com refugo >5% 66 de 225
probabilidade: 29%

In [ ]:
for turno in ['A' , 'B']:
  grupos = df[df['turno'] == turno]
  total_t = len(grupos)
  acima_t = len(grupos[grupos['refugo_pct']>5])
  prob = acima_t / total_t
  print(f'turno {turno}: {acima_t} de {total_t} = {prob:.0%}')

turno A: 3 de 106 = 3%
turno B: 63 de 119 = 53%